export enum ErrorCode {
  NETWORK_ERROR = 'NETWORK_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  MULTIPLE_BUSINESS_ERRORS = 'MULTIPLE_BUSINESS_ERRORS',
}
